spring:
  datasource:
    url: jdbc:postgresql://postgresql:5433/employee?currentSchema=dev
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
server:
  servlet:
    context-path: "/"
